# Generated by Django 5.2.4 on 2025-08-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
