# Generated by Django 5.2.4 on 2025-08-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0003_rename_title_expenses_description_expenses_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyBudget',
        ),
    ]
